### ISSUE TITLE
Avail integration

### ISSUE THREAD

**Issue by DiegoSena** [Calindra/nonodo#203]
# Tasks
## Must have
- [ ] Nonodo InputReader for Avail + InputBox (Calindra)
  - [x] #204
  - [ ] #214
  - [ ] #215
  - [ ] Extract EIP-712 from Paio format + filter inputs by DApp address
  - [ ] Release Nonodo version with Avail support
- [ ] Paio Sequencer public deployment for Avail Testnet (Zippie)
  - [ ] Configured to send batches to Avail + funded with Avail testnet tokens

## Should have
- [ ] QA (Zippie)
- [ ] Minimal tutorial / example / docs on how to use Avail with Cartesi Rollups
- [ ] `cartesi send` CLI command to submit EIP-712 inputs to Paio (Danilo)

## Nice to have
- [ ] `cartesi run` CLI command executing Nonodo + CM with networking (Barthel’s strategy)
