### ISSUE TITLE
Espresso Mainnet Alpha Integration

### ISSUE THREAD

**Issue by sandhilt** [Calindra/nonodo#230]
# Tasks
## Must have
- [ ] Node v2 with Espresso + InputBox support
  - [ ] Node v2-alpha release (Fusco/Marcelo)
  - [ ] Break up Node v2 EvmReader to isolate proper InputReader from “RollupsReader” functionality (claim and voucher status reading) (Fusco/Marcelo/Zehui)
  - [ ] Port Espresso + InputBox InputReader from Nonodo (Zehui)
  - [ ] High-level GraphQL API (Calindra)
  - [ ] /nonce and /submit endpoints
  - [ ] Release Node v2-alpha with Espresso support
- [ ] Deploy Rollups Contracts v2 on Ethereum Mainnet and/or Base
- [ ] Bug Buster on Espresso
  - [ ] Create new bounty
  - [ ] Deploy new DApp instance for new bounty on Ethereum Mainnet or Base
  - [ ] Deploy Node reading from Espresso + InputBox
  - [ ] Update front-end input submissions and output queries
  - [ ] Deploy new front-end version
## Should have
- [ ] DApp ?? on Espresso
## Nice to have
- [ ] Use Paio for Espresso
  - [x] Paio Sequencer support for Espresso
  - [ ] Paio Sequencer official deployment for Espresso Mainnet
  - [ ] Node v2 EspressoInputReader with support for Paio batch format
